# Generated by Django 5.0.4 on 2024-05-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cour',
            options={'verbose_name': 'Cour'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'verbose_name': 'Matiere'},
        ),
        migrations.AlterField(
            model_name='cour',
            name='file',
            field=models.FileField(default=None, upload_to='Cours_file'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cour',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
