# Generated by Django 5.0.4 on 2024-05-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_alter_cour_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cour',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
