# Generated by Django 5.0.4 on 2024-05-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_cour_slug_matiere_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cour',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='SchoolApp/static/Cours_file'),
        ),
    ]
