# Generated by Django 5.0.4 on 2024-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_alter_cour_file_alter_cour_title_alter_matiere_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cour',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Titre'),
        ),
    ]
